# -*- coding: utf-8 -*-
"""devanagari.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14W7bEPzR1hz4R22EWQH4n-WK-ImyWINd

# The akshara: not the syllable, is the unit of reading in Devanagari

Eye movement evidence from 141 readers and a schwa deletion natural experiment.

Question.In Devanagari, is eye movement control organised over the orthographic unit
(the akshara) or the phonological unit (the spoken syllable)? Hindi deletes the inherent
schwa कमल is 3 aksharas but 2 spoken syllables, so the two diverge for ~2/3 of words.

Data (all public).
- MECO Wave 2 Hindi, 111 readers, 2 labs (IIT Kanpur, IIIT Hyderabad), 12 texts OSF 3527a, CC-BY
- Potsdam Allahabad Hindi Eyetracking Corpus: 30 readers, 83 sentences GitHub, MIT
- Shabd psycholinguistic database: phonemic transcriptions + 2.29M type frequency list OSF xfbhd

Runtime ~15 min end to end. Runs on a free CPU Colab instance.

## 0. Setup
"""

!pip -q install pyreadr statsmodels pandas numpy matplotlib

import os, io, zipfile, urllib.request, warnings, unicodedata as ud
import numpy as np, pandas as pd, statsmodels.formula.api as smf, statsmodels.api as sm
import matplotlib.pyplot as plt
warnings.filterwarnings("ignore")
os.makedirs("data", exist_ok=True)
pd.set_option("display.width", 140)

"""1. Download datasets"""

# Download the three public datasets
def grab(url, path):
    if os.path.exists(path):
        print("cached", path); return path
    print("downloading", path, "...")
    urllib.request.urlretrieve(url, path)
    print("  ->", os.path.getsize(path), "bytes")
    return path

# MECO Wave 2 word level joint data (9.8 MB)
grab("https://osf.io/download/6996d9113ccc685cd17b0813/", "data/meco_word.rda")
# Potsdam Allahabad corpus (GitHub archive)
grab("https://github.com/vasishth/HusainEtAlJEMR2015/archive/refs/heads/master.zip", "data/pahec.zip")
# Shabd corpus (82 MB)
grab("https://osf.io/download/5f0b3eb9a6ea6e00a3fbd1f9/", "data/shabd.zip")

with zipfile.ZipFile("data/pahec.zip") as z:
    z.extract("HusainEtAlJEMR2015-master/PotsdamAllahabadHindiCorpus/data/hindi_JEMR.txt", "data")
with zipfile.ZipFile("data/shabd.zip") as z:
    for n in ["Corpus_Processing_Outcomes/SHABD_DATABASE.csv",
              "Corpus_Processing_Outcomes/words_countTotal_2.3_million"]:
        z.extract(n, "data")
print("all data ready")

"""2. Akshara segmentation and inherent schwa deletion

An akshara is a consonant (or virama bound cluster) plus a vowel, when no vowel diacritic is
written the vowel is the inherent schwa /ə/.

Deletion follows the classical right to left rule ə → ∅ / VC __ CV (Ohala 1983; Narasimhan,
Sproat & Kiraz 2004), with obligatory word final deletion and a block on deleting the first nucleus.
"""

VIRAMA, NUKTA = "\u094d", "\u093c"
CONS    = set(range(0x0915,0x093A)) | set(range(0x0958,0x0960))
INDEP_V = set(range(0x0904,0x0915))
MATRA   = set(range(0x093A,0x094D)) | {0x094E,0x094F,0x0955,0x0956,0x0957,0x0962,0x0963}
SIGNS   = {0x0900,0x0901,0x0902,0x0903}
PUNCT   = "\u0964\u0965,.!?\"'()-\u2013\u2014;:%\u2026\u2018\u2019\u201c\u201d\u200d\u200c"

def strip_punct(w):
    return "".join(c for c in str(w) if c not in PUNCT).strip()

def parse_aksharas(w):
    """list of {onset: n_consonants, vowel: inherent|explicit|independent|none}"""
    out, i, n = [], 0, len(w)
    while i < n:
        cp = ord(w[i])
        if cp in INDEP_V:
            out.append({"onset":0,"vowel":"independent"}); i += 1
            while i < n and (ord(w[i]) in SIGNS or w[i] == NUKTA): i += 1
        elif cp in CONS:
            ncons, i = 1, i+1
            while i < n and w[i] == NUKTA: i += 1
            while i < n and w[i] == VIRAMA:          # conjunct: C + virama + C
                i += 1
                if i < n and ord(w[i]) in CONS:
                    ncons += 1; i += 1
                    while i < n and w[i] == NUKTA: i += 1
                else:
                    out.append({"onset":ncons,"vowel":"none"}); ncons = 0; break
            if ncons == 0: continue
            if i < n and ord(w[i]) in MATRA:
                out.append({"onset":ncons,"vowel":"explicit"}); i += 1
            else:
                out.append({"onset":ncons,"vowel":"inherent"})
            while i < n and (ord(w[i]) in SIGNS or ord(w[i]) in MATRA): i += 1
        else:
            i += 1
    return out

def n_aksharas(w):
    return sum(1 for a in parse_aksharas(w) if a["vowel"] != "none")

def syllables_after_deletion(w):
    ak = parse_aksharas(w)
    if not ak: return np.nan
    alive = [a["vowel"] != "none" for a in ak]
    for j in range(len(ak)-1, -1, -1):
        if ak[j]["vowel"] != "inherent" or not alive[j] or j == 0: continue
        if not any(alive[k] and ak[k]["vowel"] != "none" for k in range(j)): continue
        if j == len(ak)-1:
            alive[j] = False                                   # word-final schwa
        elif alive[j+1] and ak[j+1]["onset"] > 0:
            alive[j] = False                                   # VC __ CV
    return sum(1 for j,a in enumerate(ak) if alive[j] and a["vowel"] != "none")

for w in ["\u0915\u092e\u0932","\u092c\u091a\u092a\u0928","\u0936\u0939\u0930","\u0930\u093e\u0938\u094d\u0924\u093e"]:
    print(f"{w}  aksharas={n_aksharas(w)}  spoken syllables={syllables_after_deletion(w)}")

"""3. Validate the rule against Shabd's phonemic transcriptions

A hand built rule is exactly what a reviewer should distrust, so it is checked against an external gold standard before being used.
"""

S = pd.read_csv("data/Corpus_Processing_Outcomes/SHABD_DATABASE.csv")
VOW = set("aiueo\u025b\u0254\u0259\u00e6\u0251\u028a\u026a")

def gold_syllables(p):
    if not isinstance(p, str): return np.nan
    p = ud.normalize("NFD", p.replace(":","").replace("'",""))
    return sum(1 for ch in p if ch.lower() in VOW)

S["w"]     = S.word.map(strip_punct)
S["gold"]  = S.phonemes.map(gold_syllables)
S["pred"]  = S.w.map(syllables_after_deletion)
S["ak"]    = S.w.map(n_aksharas)
S["nukta"] = S.w.map(lambda x: NUKTA in x or any(0x0958 <= ord(c) <= 0x095F for c in x))

v  = S.dropna(subset=["gold","pred"])
vn = v[~v.nukta]     # Shabd inserts a spurious schwa for nukta consonants
print(f"validation words                : {len(v)}")
print(f"exact syllable count match      : {100*(v.pred==v.gold).mean():.1f}%")
print(f"  within 1                      : {100*((v.pred-v.gold).abs()<=1).mean():.1f}%")
print(f"  correlation                   : {v.pred.corr(v.gold):.3f}")
print(f"excluding nukta words ({len(vn)}) : {100*(vn.pred==vn.gold).mean():.1f}%")
print(f"baseline raw akshara count      : {100*(vn.ak==vn.gold).mean():.1f}%")
print(f"\nakshara vs spoken agree for only {100*(v.ak==v.gold).mean():.1f}% of words")
print(f"mean aksharas {v.ak.mean():.2f} vs mean spoken syllables {v.gold.mean():.2f}")
verified = set(S.loc[S.pred == S.gold, "w"])

"""4. Frequency norms (Shabd, 2.29M types / 1.33B tokens)"""

F = pd.read_csv("data/Corpus_Processing_Outcomes/words_countTotal_2.3_million",
                sep="\t", header=None, names=["w","count","len"], quoting=3)
F = F.dropna(subset=["w"]); F["w"] = F.w.astype(str).map(strip_punct)
F = F[F.w.str.len() > 0].groupby("w", as_index=False)["count"].sum()
TOT = F["count"].sum()
F["zipf"] = np.log10(F["count"] / TOT * 1e9)
FREQ = dict(zip(F.w, F.zipf))
print(f"{len(F):,} types over {TOT/1e9:.2f}B tokens")

def predictors(words):
    u = pd.DataFrame({"w": sorted(set(words))})
    u["akshara"] = u.w.map(n_aksharas)
    u["psyll"]   = u.w.map(syllables_after_deletion)
    u["nchar"]   = u.w.str.len()
    u["zipf"]    = u.w.map(FREQ)
    u["nukta"]   = u.w.map(lambda x: NUKTA in x or any(0x0958 <= ord(c) <= 0x095F for c in x))
    u["delta"]   = u.akshara - u.psyll      # number of deleted schwas
    return u

"""5. Build the analysis frames"""

import pyreadr
d = pyreadr.read_r("data/meco_word.rda")["joint.data"]
m = d[d.lang.isin(["hi_iitk","hi_iiith"])].copy()
m["w"] = m.word.map(strip_punct); m = m[m.w.str.len() > 0]
m = m.merge(predictors(m.w), on="w", how="left")
m = m.rename(columns={"firstfix.dur":"ffd","firstrun.dur":"gaze","firstrun.gopast":"gopast",
                      "firstfix.land":"land","uniform_id":"subj","itemid":"item"})
m["lab"] = m.lang
m["pos"] = m.item.astype(str) + "_" + m.wordnum.astype(str)

p = pd.read_csv("data/HusainEtAlJEMR2015-master/PotsdamAllahabadHindiCorpus/data/hindi_JEMR.txt",
                sep=r"\s+", quotechar='"')
p["w"] = p.word_lex.map(strip_punct); p = p[p.w.str.len() > 0]
p = p.merge(predictors(p.w), on="w", how="left")
p = p.rename(columns={"FFD":"ffd","FPRT":"gaze","RPD":"gopast","TFT":"tft"})

print(f"MECO  : {len(m):,} rows | {m.subj.nunique()} readers | "
      f"zipf coverage {100*m.zipf.notna().mean():.1f}% | syllable coverage {100*m.psyll.notna().mean():.1f}%")
print(f"PAHEC : {len(p):,} rows | {p.subj.nunique()} readers")
print(m.groupby("lab").agg(readers=("subj","nunique"), texts=("item","nunique"), tokens=("w","size")))

mt = m.drop_duplicates("pos")
print("\ndivergence (aksharas - spoken syllables) across distinct word positions:")
print(mt.delta.value_counts().sort_index().to_string())
print("\ncorrelations among the three length metrics:")
print(mt[["akshara","psyll","nchar"]].corr().round(3).to_string())

"""6. Main model comparison

Linear mixed effects models on log durations, crossed random effects for reader and text,
controlling Zipf frequency and word position. Negative ΔAIC favours the akshara.
"""

def prep(d, poscol):
    d = d.dropna(subset=["akshara","psyll","nchar","zipf"]).copy()
    for c in ["akshara","psyll","nchar","zipf",poscol]:
        d["c_"+c] = (d[c] - d[c].mean()) / d[c].std()
    d["c_wpos"] = d["c_"+poscol]
    return d

M = prep(m, "wordnum"); P = prep(p, "roi")

def fit(d, dv, rhs, grp="subj", vc="item"):
    d = d[(d[dv].notna()) & (d[dv] > 0)]
    return smf.mixedlm(f"np.log({dv}) ~ {rhs}", d, groups=d[grp],
                       vc_formula={vc: "0 + C(%s)" % vc}
                       ).fit(reml=False, method="lbfgs", maxiter=2000), len(d)

CTRL = "c_zipf + c_wpos"
GRID = {"base":CTRL, "+ nchar":CTRL+" + c_nchar", "+ akshara":CTRL+" + c_akshara",
        "+ spoken syllables":CTRL+" + c_psyll",
        "+ all three":CTRL+" + c_nchar + c_akshara + c_psyll"}

for dv, lab in [("ffd","first fixation duration"), ("gaze","Gaze duration"),
                ("gopast","Go past duration")]:
    print("="*74); print(f"{lab}"); print("="*74)
    res = {}
    for name, rhs in GRID.items():
        r, n = fit(M, dv, rhs); res[name] = r
        print(f"  {name:20s} AIC={r.aic:10.1f}")
    r = res["+ all three"]
    print("  coefficients (all three):", "  ".join(
        f"{t.replace('c_','')} b={r.params[t]:+.4f} p={r.pvalues[t]:.2g}"
        for t in ["c_nchar","c_akshara","c_psyll"]))
    dA = res["+ akshara"].aic - res["+ spoken syllables"].aic
    print(f" head tohead dAIC = {dA:+.1f}  "
          f"({'Akshara' if dA < 0 else 'Spoken syllable'} wins)\n")

"""7. Where does the eye land? (oculomotor targeting)"""

L = M[(M.land.notna()) & (M.land > 0) & (M.skip == 0)]
print(f"n = {len(L):,} first fixations, mean landing position {L.land.mean():.2f} characters\n")
for name, rhs in [("characters only","nchar"), ("spoken syllables only","psyll"),
                  ("aksharas only","akshara"), ("characters + aksharas","nchar + akshara"),
                  ("all three","nchar + akshara + psyll")]:
    r = smf.mixedlm(f"land ~ {rhs}", L, groups=L["subj"], vc_formula={"item":"0 + C(item)"}
                    ).fit(reml=False, method="lbfgs", maxiter=2000)
    extra = "  ".join(f"{t} b={r.params[t]:+.3f} p={r.pvalues[t]:.2g}"
                      for t in ["nchar","akshara","psyll"] if t in r.params)
    print(f"  {name:24s} AIC={r.aic:10.1f} | {extra}")

print("\n Skipping(logistic GEE, reader clustered)")
s = M.dropna(subset=["skip"])
for name, rhs in [("nchar","c_zipf + c_wpos + c_nchar"), ("akshara","c_zipf + c_wpos + c_akshara"),
                  ("spoken","c_zipf + c_wpos + c_psyll")]:
    g = smf.gee("skip ~ "+rhs, groups="subj", data=s, family=sm.families.Binomial()).fit()
    print(f"  {name:8s} QIC={g.qic()[0]:10.1f}")

"""8. Replication: two labs, an independent corpus, and held-out

readers
"""

print("Per lab (MECO reads identical materials at two institutions)")
for lab in ["hi_iitk","hi_iiith"]:
    s = M[M.lab == lab]
    print(f"  {lab} ({s.subj.nunique()} readers) ")
    for dv in ["ffd","gaze","gopast"]:
        ra,_ = fit(s, dv, CTRL+" + c_akshara"); rp,_ = fit(s, dv, CTRL+" + c_psyll")
        print(f"     {dv:7s} dAIC={ra.aic-rp.aic:+9.1f}  {'Akshara' if ra.aic<rp.aic else 'Spoken'}")

print("\n Independent corpus: Potsdam Allahabad (different lab, genre and decade)")
for dv in ["ffd","gaze","gopast","tft"]:
    ra,_ = fit(P, dv, "c_zipf + c_wpos + c_akshara"); rp,n = fit(P, dv, "c_zipf + c_wpos + c_psyll")
    print(f"  {dv:7s} n={n:6d} dAIC={ra.aic-rp.aic:+9.1f}  {'Akshara' if ra.aic<rp.aic else 'Spoken'}")

print("\nCross validation on held out readers (5 fold)")
rng = np.random.default_rng(1)
subs = M.subj.unique().copy(); rng.shuffle(subs); folds = np.array_split(subs, 5)
for dv in ["ffd","gaze","gopast"]:
    d = M[(M[dv].notna()) & (M[dv] > 0)].copy(); d["y"] = np.log(d[dv])
    sc = {}
    for name, rhs in [("nchar","zipf + nchar"), ("akshara","zipf + akshara"), ("spoken","zipf + psyll")]:
        sc[name] = np.mean([np.mean((d[d.subj.isin(f)].y -
                    smf.ols("y ~ "+rhs, d[~d.subj.isin(f)]).fit().predict(d[d.subj.isin(f)]))**2)
                    for f in folds])
    print(f"  {dv:7s} held-out MSE " + "  ".join(f"{k}={v:.5f}" for k,v in sc.items())
          + f"   -> {min(sc, key=sc.get).upper()} best")

"""9. The schwa deletion conversion cost and its failure to replicate

Holding akshara count constant, does each deleted schwa cost extra time? This is the one
result we do not claim: it is solid within MECO and replicates at both labs, but reverses
sign in the Potsdam Allahabad corpus.
"""

def with_delta(d):
    return d.assign(c_delta=(d.delta - d.delta.mean()) / d.delta.std())

RHS = "c_zipf + c_wpos + c_nchar + c_akshara + c_delta"

print("MECO pooled and per lab (delta = number of deleted schwas)")
for name, d in [("pooled", M), ("IITK", M[M.lab=="hi_iitk"]), ("IIITH", M[M.lab=="hi_iiith"])]:
    cells = []
    for dv in ["ffd","gaze","gopast"]:
        r, _ = fit(with_delta(d), dv, RHS)
        cells.append(f"{dv}: b={r.params['c_delta']:+.4f} p={r.pvalues['c_delta']:.2g}")
    print(f"  {name:7s} " + "   ".join(cells))

print("\nPAHEC the sign reverses")
for dv in ["gaze","gopast"]:
    r, _ = fit(with_delta(P), dv, RHS)
    print(f"  {dv:7s} b={r.params['c_delta']:+.4f} p={r.pvalues['c_delta']:.2g}")

"""10. Effect sizes in milliseconds, and robustness"""

print("Effect sizes (raw, unstandardised)")
for dv, lab in [("ffd","first-fixation"), ("gaze","gaze"), ("gopast","go-past")]:
    d = M[(M[dv].notna()) & (M[dv] > 0)]
    r = smf.mixedlm(f"np.log({dv}) ~ zipf + wordnum + nchar + akshara + delta", d,
                    groups=d["subj"], vc_formula={"item":"0 + C(item)"}
                    ).fit(reml=False, method="lbfgs", maxiter=2000)
    base = np.exp(r.params["Intercept"] + sum(r.params[k]*d[k].mean()
                  for k in ["zipf","wordnum","nchar","akshara","delta"]))
    print(f"  {lab:15s} mean={d[dv].mean():6.1f}ms | +1 akshara={base*(np.exp(r.params['akshara'])-1):+6.1f}ms"
          f" | +1 deleted schwa={base*(np.exp(r.params['delta'])-1):+5.1f}ms")

print("\n Robustness (gaze duration; dAIC negative = akshara wins)")
subsets = {
    "all words": M,
    "excluding nukta words": M[~M.nukta.astype(bool)],
    "excluding conjuncts": M[~M.w.astype(str).str.contains(VIRAMA)],
    "only Shabd verified syllabifications": M[M.w.isin(verified)],
    "content words (>=3 chars)": M[M.nchar >= 3],
    "excluding 200 most frequent types": M[~M.w.isin(M.w.value_counts().head(200).index)],
}
for name, s in subsets.items():
    ra,_ = fit(s, "gaze", CTRL+" + c_akshara"); rp,n = fit(s, "gaze", CTRL+" + c_psyll")
    print(f"  {name:38s} n={n:6d}  dAIC={ra.aic-rp.aic:+9.1f}")

"""11. Figures"""

# recompute every number shown, so the figure cannot drift from the analysis
bars = []
for dv, lab in [("ffd","first fix"), ("gaze","gaze"), ("gopast","go-past")]:
    ra, _ = fit(M, dv, CTRL + " + c_akshara")
    rp, _ = fit(M, dv, CTRL + " + c_psyll")
    bars.append((lab, ra.aic - rp.aic))
la = smf.mixedlm("land ~ akshara", L, groups=L["subj"], vc_formula={"item":"0 + C(item)"}
                 ).fit(reml=False, method="lbfgs", maxiter=2000)
lc = smf.mixedlm("land ~ nchar", L, groups=L["subj"], vc_formula={"item":"0 + C(item)"}
                 ).fit(reml=False, method="lbfgs", maxiter=2000)
bars.append(("landing pos", la.aic - lc.aic))
print("dAIC values plotted:", [(b[0], round(b[1],1)) for b in bars])

fig, ax = plt.subplots(1, 3, figsize=(15, 4.2))

mt = M.drop_duplicates("pos")
ax[0].hist([mt.akshara.dropna(), mt.psyll.dropna()], bins=range(1,10),
           label=["aksharas", "spoken syllables"])
ax[0].set_xlabel("units per word"); ax[0].set_ylabel("word positions")
ax[0].set_title("The script writes more units\nthan the language speaks"); ax[0].legend()

ax[1].barh([b[0] for b in bars], [b[1] for b in bars], color="#b2182b")
ax[1].axvline(0, color="k", lw=.8)
ax[1].set_xlabel(r"$\Delta$AIC (negative favours akshara)")
ax[1].set_title("Akshara beats the competing unit\non every measure")

g  = M[M.gaze > 0].groupby("akshara").gaze.mean()
g2 = M[M.gaze > 0].groupby("psyll").gaze.mean()
ax[2].plot(g.index, g.values, "o-", label="by akshara count")
ax[2].plot(g2.index, g2.values, "s--", label="by spoken syllable count")
ax[2].set_xlabel("units"); ax[2].set_ylabel("mean gaze duration (ms)")
ax[2].set_title("Raw means by unit count\n(descriptive only, the claim rests on\nthe model comparison in panel 2)")
ax[2].legend()

plt.tight_layout(); plt.savefig("figure1.png", dpi=160); plt.show()

"""## 12. Summary

| Claim | Status |
|---|---|
| The akshara beats the spoken syllable on every duration measure | 6 tests, 6 wins across 3 samples |
| The akshara beats raw character count | yes, most decisively on landing position |
| Saccades are targeted in akshara space | ΔAIC = −10,459; character coefficient reverses |
| Generalises to unseen readers | held-out CV, 3/3 measures |
| Schwa deletion imposes a conversion cost | not claimed — replicates in MECO, reverses in PAHEC |

Biggest known weakness: visual extent is indexed by character count, not rendered pixel
width. Fixing that with the real stimulus font is the first extension.

"""