# -*- coding: utf-8 -*-
"""safal_akshara_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FJ9pA-CFp77n2EALn58z-USJapBeKfys

Aksharas, spoken syllables and rendered width in Hindi reading

Width adjusted eye movement evidence from 141 readers and a schwa-deletion natural experiment.

Question. In Devanagari is eye movement control organised over the orthographic unit
(the akshara) or the phonological unit (the spoken syllable), after controlling for actual
rendered word width? Hindi deletes the inherent schwa कमल is 3 aksharas but 2 spoken syllables
so the two measures can diverge even for the same written word.

Data (all public).
- MECO Wave 2 Hindi 111 readers, 2 labs (IIT Kanpur, IIIT Hyderabad), 12 texts OSF 3527a, CC-BY
- Potsdam Allahabad Hindi Eyetracking Corpus 30 readers, 83 sentences GitHub, MIT
- Shabd psycholinguistic database phonemic transcriptions + 2.29M type frequency list OSF xfbhd

Important font limitation. MECO used proprietary Microsoft Kokila. Unless you have a separate licence that expressly permits using that font on a remote server, this Colab uses a
lawfully available opensource Devanagari font as a width proxy. The exact image validation also
downloads the public original MECO stimulus archive, approximately 22.4 MB, unless an existing
archive is supplied through MECO_BITMAPS_PATH.

Runs on a free CPU Colab instance; first run downloads the public datasets.

## 0. Setup
"""

import importlib.util, subprocess, sys

required_packages = {
    "pyreadr": "pyreadr", "statsmodels": "statsmodels", "pandas": "pandas",
    "numpy": "numpy", "matplotlib": "matplotlib", "uharfbuzz": "uharfbuzz",
    "PIL": "pillow", "scipy": "scipy",
}
missing_packages = [package for module, package in required_packages.items()
                    if importlib.util.find_spec(module) is None]
if missing_packages:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", *missing_packages])
else:
    print("Scientific dependencies already installed.")

import os, io, zipfile, urllib.request, warnings, unicodedata as ud
from functools import lru_cache
import numpy as np, pandas as pd, statsmodels.formula.api as smf, statsmodels.api as sm
import matplotlib.pyplot as plt
import uharfbuzz as hb
warnings.filterwarnings("ignore")
os.makedirs("data", exist_ok=True)
pd.set_option("display.width", 140)

"""## 1. Download the three public datasets"""

def grab(url, path):
    if os.path.exists(path):
        print("cached", path); return path
    print("downloading", path, "...")
    urllib.request.urlretrieve(url, path)
    print("  ->", os.path.getsize(path), "bytes")
    return path

# MECO Wave 2 word level joint data (9.8 MB)
grab("https://osf.io/download/6996d9113ccc685cd17b0813/", "data/meco_word.rda")
# Potsdam Allahabad corpus (GitHub archive)
grab("https://github.com/vasishth/HusainEtAlJEMR2015/archive/refs/heads/master.zip", "data/pahec.zip")
# Shabd corpus (82 MB)
grab("https://osf.io/download/5f0b3eb9a6ea6e00a3fbd1f9/", "data/shabd.zip")

with zipfile.ZipFile("data/pahec.zip") as z:
    z.extract("HusainEtAlJEMR2015-master/PotsdamAllahabadHindiCorpus/data/hindi_JEMR.txt", "data")
with zipfile.ZipFile("data/shabd.zip") as z:
    for n in ["Corpus_Processing_Outcomes/SHABD_DATABASE.csv",
              "Corpus_Processing_Outcomes/words_countTotal_2.3_million"]:
        z.extract(n, "data")
print("all data ready")

"""1a. Measure shaped Devanagari glyph width

HarfBuzz performs the same kind of glyph shaping used by text renderers: conjuncts, vowel signs,
and ligatures contribute their actual advances rather than being counted as independent Unicode
characters. width_em is font size independent. width_px additionally assumes 28 point type
and a configurable rendering DPI; the original rendering DPI was not released.

MECO used Kokila, a proprietary font. Use KOKILA_FONT only if you already hold rights that expressly allow that font in the environment where this notebook runs. Otherwise use the
opensource Noto proxy. The original MECO stimulus bitmaps are the best exact pixel reference
and do not require redistributing Kokila:

- [MECO original stimulus raster archive v2.1 (preferred)](https://osf.io/download/3eu49/)
- [MECO original stimulus raster archive v2.0 (legacy)](https://osf.io/download/4tegp/)

The exact image validation below downloads the public v2.1 archive automatically, unless
MECO_BITMAPS_PATH already points to a local copy. The older v2.0 archive remains an optional manual reference. Original image ink bounds are archival image pixels, not screen pixels.

"""

licensed_font = os.environ.get("KOKILA_FONT", "")
if licensed_font and not os.path.isfile(licensed_font):
    raise FileNotFoundError("KOKILA_FONT does not point to an existing licensed font file")

FONT = licensed_font or next(
    (path for path in ["data/deva.ttf", "../nbtest2/data/deva.ttf"] if os.path.isfile(path)),
    "data/deva.ttf",
)
if not os.path.isfile(FONT):
    urllib.request.urlretrieve(
        "https://github.com/google/fonts/raw/main/ofl/notosansdevanagari/"
        "NotoSansDevanagari%5Bwdth%2Cwght%5D.ttf",
        FONT,
    )

face = hb.Face(hb.Blob.from_file_path(FONT), 0)
shaping_font = hb.Font(face)
STIMULUS_FONT_PT = 28
RENDER_DPI = float(os.environ.get("STIMULUS_RENDER_DPI", "96"))

@lru_cache(maxsize=None)
def rendered_width_em(word):
    buf = hb.Buffer()
    buf.add_str(str(word))
    buf.guess_segment_properties()
    hb.shape(shaping_font, buf)
    return sum(position.x_advance for position in buf.glyph_positions) / face.upem

print("font:", FONT)
print("font status:", "user-supplied licensed font" if licensed_font else "open-source proxy; NOT original Kokila")
print(f"pixel conversion: {STIMULUS_FONT_PT} pt at {RENDER_DPI:g} assumed DPI")
print("Actual Kokila stimulus pixels and rendering DPI require the released MECO stimulus bitmaps.")

"""2. Akshara segmentation and inherent-schwa deletion

An akshara is a consonant (or virama bound cluster) plus a vowel; when no vowel diacritic is
written the vowel is the inherent schwa /ə/.

Deletion follows the classical right to left rule ə -> ∅ / VC __ CV (Ohala 1983; Narasimhan,
Sproat & Kiraz 2004), with obligatory word final deletion and a block on deleting the first
nucleus.
"""

VIRAMA, NUKTA = "\u094d", "\u093c"
CONS    = set(range(0x0915,0x093A)) | set(range(0x0958,0x0960))
INDEP_V = set(range(0x0904,0x0915))
MATRA   = set(range(0x093A,0x094D)) | {0x094E,0x094F,0x0955,0x0956,0x0957,0x0962,0x0963}
SIGNS   = {0x0900,0x0901,0x0902,0x0903}
PUNCT   = "\u0964\u0965,.!?\"'()-\u2013\u2014;:%\u2026\u2018\u2019\u201c\u201d\u200d\u200c"

def strip_punct(w):
    return "".join(c for c in str(w) if c not in PUNCT).strip()

def parse_aksharas(w):
    """-> list of {onset: n_consonants, vowel: inherent|explicit|independent|none}"""
    out, i, n = [], 0, len(w)
    while i < n:
        cp = ord(w[i])
        if cp in INDEP_V:
            out.append({"onset":0,"vowel":"independent"}); i += 1
            while i < n and (ord(w[i]) in SIGNS or w[i] == NUKTA): i += 1
        elif cp in CONS:
            ncons, i = 1, i+1
            while i < n and w[i] == NUKTA: i += 1
            while i < n and w[i] == VIRAMA:          # conjunct: C + virama + C
                i += 1
                if i < n and ord(w[i]) in CONS:
                    ncons += 1; i += 1
                    while i < n and w[i] == NUKTA: i += 1
                else:
                    out.append({"onset":ncons,"vowel":"none"}); ncons = 0; break
            if ncons == 0: continue
            if i < n and ord(w[i]) in MATRA:
                out.append({"onset":ncons,"vowel":"explicit"}); i += 1
            else:
                out.append({"onset":ncons,"vowel":"inherent"})
            while i < n and (ord(w[i]) in SIGNS or ord(w[i]) in MATRA): i += 1
        else:
            i += 1
    return out

def n_aksharas(w):
    return sum(1 for a in parse_aksharas(w) if a["vowel"] != "none")

def syllables_after_deletion(w):
    ak = parse_aksharas(w)
    if not ak: return np.nan
    alive = [a["vowel"] != "none" for a in ak]
    for j in range(len(ak)-1, -1, -1):
        if ak[j]["vowel"] != "inherent" or not alive[j] or j == 0: continue
        if not any(alive[k] and ak[k]["vowel"] != "none" for k in range(j)): continue
        if j == len(ak)-1:
            alive[j] = False                                   # word-final schwa
        elif alive[j+1] and ak[j+1]["onset"] > 0:
            alive[j] = False                                   # VC __ CV
    return sum(1 for j,a in enumerate(ak) if alive[j] and a["vowel"] != "none")

for w in ["\u0915\u092e\u0932","\u092c\u091a\u092a\u0928","\u0936\u0939\u0930","\u0930\u093e\u0938\u094d\u0924\u093e"]:
    print(f"{w}  aksharas={n_aksharas(w)}  spoken syllables={syllables_after_deletion(w)}")

"""3. Validate the rule against Shabd's phonemic transcriptions

A hand built rule is exactly what a reviewer should distrust so it is checked against an external gold standard before being used.
"""

S = pd.read_csv("data/Corpus_Processing_Outcomes/SHABD_DATABASE.csv")
VOW = set("aiueo\u025b\u0254\u0259\u00e6\u0251\u028a\u026a")

def gold_syllables(p):
    if not isinstance(p, str): return np.nan
    p = ud.normalize("NFD", p.replace(":","").replace("'",""))
    return sum(1 for ch in p if ch.lower() in VOW)

S["w"]     = S.word.map(strip_punct)
S["gold"]  = S.phonemes.map(gold_syllables)
S["pred"]  = S.w.map(syllables_after_deletion)
S["ak"]    = S.w.map(n_aksharas)
S["nukta"] = S.w.map(lambda x: NUKTA in x or any(0x0958 <= ord(c) <= 0x095F for c in x))

v  = S.dropna(subset=["gold","pred"])
vn = v[~v.nukta]     # Shabd inserts a spurious schwa for nukta consonants
print(f"validation words                : {len(v)}")
print(f"exact syllable count match      : {100*(v.pred==v.gold).mean():.2f}%")
print(f"  within 1                      : {100*((v.pred-v.gold).abs()<=1).mean():.2f}%")
print(f"  correlation                   : {v.pred.corr(v.gold):.3f}")
print(f"excluding nukta words ({len(vn)}) : {100*(vn.pred==vn.gold).mean():.2f}%")
print(f"Baseline raw akshara count      : {100*(vn.ak==vn.gold).mean():.2f}%")
print(f"\nakshara vs spoken agree for only {100*(v.ak==v.gold).mean():.1f}% of words")
print(f"mean aksharas {v.ak.mean():.2f} vs mean spoken syllables {v.gold.mean():.2f}")
verified = set(S.loc[S.pred == S.gold, "w"])

"""4. Frequency norms (Shabd, 2.29M types / 1.33B tokens)"""

F = pd.read_csv("data/Corpus_Processing_Outcomes/words_countTotal_2.3_million",
                sep="\t", header=None, names=["w","count","len"], quoting=3)
F = F.dropna(subset=["w"]); F["w"] = F.w.astype(str).map(strip_punct)
F = F[F.w.str.len() > 0].groupby("w", as_index=False)["count"].sum()
TOT = F["count"].sum()
F["zipf"] = np.log10(F["count"] / TOT * 1e9)
FREQ = dict(zip(F.w, F.zipf))
print(f"{len(F):,} types over {TOT/1e9:.2f}B tokens")

def predictors(words):
    u = pd.DataFrame({"w": sorted(set(words))})
    u["akshara"] = u.w.map(n_aksharas)
    u["psyll"]   = u.w.map(syllables_after_deletion)
    u["nchar"]   = u.w.str.len()
    u["width_em"] = u.w.map(rendered_width_em)
    u["width_px"] = u.width_em * STIMULUS_FONT_PT * RENDER_DPI / 72
    u["zipf"]    = u.w.map(FREQ)
    u["nukta"]   = u.w.map(lambda x: NUKTA in x or any(0x0958 <= ord(c) <= 0x095F for c in x))
    u["delta"]   = u.akshara - u.psyll      # number of deleted schwas
    return u

"""5 Build the analysis frames"""

import pyreadr
d = pyreadr.read_r("data/meco_word.rda")["joint.data"]
m = d[d.lang.isin(["hi_iitk","hi_iiith"])].copy()
m["w"] = m.word.map(strip_punct); m = m[m.w.str.len() > 0]
m = m.merge(predictors(m.w), on="w", how="left")
m = m.rename(columns={"firstfix.dur":"ffd","firstrun.dur":"gaze","firstrun.gopast":"gopast",
                      "firstfix.land":"land","uniform_id":"subj","itemid":"item"})
m["item"] = pd.to_numeric(m["item"], errors="raise").astype(int)
m["wordnum"] = pd.to_numeric(m["wordnum"], errors="raise").astype(int)
m["lab"] = m.lang
m["pos"] = m.item.astype(str) + "_" + m.wordnum.astype(str)

p = pd.read_csv("data/HusainEtAlJEMR2015-master/PotsdamAllahabadHindiCorpus/data/hindi_JEMR.txt",
                sep=r"\s+", quotechar='"')
p["w"] = p.word_lex.map(strip_punct); p = p[p.w.str.len() > 0]
p = p.merge(predictors(p.w), on="w", how="left")
p = p.rename(columns={"FFD":"ffd","FPRT":"gaze","RPD":"gopast","TFT":"tft"})
p["lab"] = "pahec"

print(f"MECO  : {len(m):,} rows | {m.subj.nunique()} readers | {m.w.nunique()} word types | "
      f"zipf coverage {100*m.zipf.notna().mean():.1f}% | syllable coverage {100*m.psyll.notna().mean():.1f}%")
print(f"PAHEC : {len(p):,} rows | {p.subj.nunique()} readers | {p.item.nunique()} items")
print(m.groupby("lab").agg(readers=("subj","nunique"), texts=("item","nunique"), tokens=("w","size")))

mt = m.drop_duplicates("pos")
print("\ndivergence (aksharas spoken syllables) across distinct word positions:")
print(mt.delta.value_counts().sort_index().to_string())
print("\ncorrelations among orthographic, spoken, character, and shaped-width measures:")
print(mt[["akshara","psyll","nchar","width_em"]].corr().round(3).to_string())
print("\nexample shaped word widths:")
print(mt[["w","akshara","psyll","nchar","width_em","width_px"]].head(8).round(3).to_string(index=False))

"""6 Main model comparison

OLS models on log durations, with standard errors clustered by reader. Every comparison controls
Zipf frequency, word position, laboratory, and HarfBuzz shaped rendered word width.
Negative ΔAIC favours the akshara; significance does not imply a large predictive gain.
"""

def prep(d, poscol):
    d = d.dropna(subset=["akshara","psyll","nchar","zipf","width_em"]).copy()
    for c in ["akshara","psyll","nchar","zipf","width_em",poscol]:
        d["c_"+c] = (d[c] - d[c].mean()) / d[c].std()
    d["c_wpos"] = d["c_"+poscol]
    return d

M = prep(m, "wordnum"); P = prep(p, "roi")

def fit(d, dv, rhs, grp="subj", vc="item"):
    d = d[(d[dv].notna()) & (d[dv] > 0)]
    model = smf.ols(f"np.log({dv}) ~ {rhs}", d).fit(
        cov_type="cluster", cov_kwds={"groups": d[grp]}
    )
    return model, len(d)

CTRL = "c_zipf + c_wpos + c_width_em + C(lab)"
GRID = {"base":CTRL, "+ nchar":CTRL+" + c_nchar", "+ akshara":CTRL+" + c_akshara",
        "+ spoken syllables":CTRL+" + c_psyll",
        "+ all three":CTRL+" + c_nchar + c_akshara + c_psyll"}

ADJUSTED_DAIC = {}
for dv, lab in [("ffd","First fixation duration"), ("gaze","Gaze duration"),
                ("gopast","Go past duration")]:
    print(f"{lab}");
    res = {}
    for name, rhs in GRID.items():
        r, n = fit(M, dv, rhs); res[name] = r
        print(f"  {name:20s} AIC={r.aic:10.1f}")
    r = res["+ all three"]
    print("  coefficients (all three):", "  ".join(
        f"{t.replace('c_','')} b={r.params[t]:+.4f} p={r.pvalues[t]:.2g}"
        for t in ["c_nchar","c_akshara","c_psyll"]))
    dA = res["+ akshara"].aic - res["+ spoken syllables"].aic
    ADJUSTED_DAIC[dv] = dA
    raw, n = fit(M, dv, CTRL+" + akshara")
    print(f"  unstandardized akshara: b={raw.params['akshara']:+.6f} per additional akshara "
          f"p={raw.pvalues['akshara']:.3g} n={n:,}")
    print(f"  head to head dAIC = {dA:+.3f}  "
          f"({'Akshara' if dA < 0 else 'Spoken syllable'} wins)\n")

"""7 Landing position: exploratory, not decisive evidence

MECO's firstfix.land is recorded as an integer character index, not a physical pixel or glyph coordinate. Even a width adjusted association cannot establish where the eye landed in actual rendered stimulus space. We report this analysis only as an exploratory sensitivity check.

"""

L = M[(M.land.notna()) & (M.land > 0) & (M.skip == 0)]
print(f"n = {len(L):,} first fixations; mean landing position {L.land.mean():.2f} characters\n")
for name, rhs in [("characters + width","width_em + nchar"),
                  ("spoken syllables + width","width_em + psyll"),
                  ("aksharas + width","width_em + akshara"),
                  ("all counts + width","width_em + nchar + akshara + psyll")]:
    r = smf.ols(f"land ~ {rhs} + C(lab)", L).fit(
        cov_type="cluster", cov_kwds={"groups": L["subj"]}
    )
    extra = "  ".join(f"{t} b={r.params[t]:+.3f} p={r.pvalues[t]:.2g}"
                      for t in ["nchar","akshara","psyll"] if t in r.params)
    print(f"  {name:24s} AIC={r.aic:10.1f} | {extra}")

print("\nSkipping(logistic GEE, reader clustered)")
s = M.dropna(subset=["skip"])
for name, rhs in [("nchar",CTRL+" + c_nchar"), ("akshara",CTRL+" + c_akshara"),
                  ("spoken",CTRL+" + c_psyll")]:
    g = smf.gee("skip ~ "+rhs, groups="subj", data=s, family=sm.families.Binomial()).fit()
    print(f"  {name:8s} QIC={g.qic()[0]:10.1f}")

"""8 Replication: two labs, an independent corpus, and held-out readers"""

print("Per lab (MECO reads identical materials at two institutions)")
for lab in ["hi_iitk","hi_iiith"]:
    s = M[M.lab == lab]
    print(f" {lab} ({s.subj.nunique()} readers)")
    for dv in ["ffd","gaze","gopast"]:
        ra,_ = fit(s, dv, CTRL+" + c_akshara"); rp,_ = fit(s, dv, CTRL+" + c_psyll")
        raw,n = fit(s, dv, CTRL+" + akshara")
        print(f"     {dv:7s} n={n:6d} dAIC={ra.aic-rp.aic:+9.3f} "
              f"b={raw.params['akshara']:+.6f} p={raw.pvalues['akshara']:.3g} "
              f"{'Akshara' if ra.aic<rp.aic else 'SPOKEN'}")

print("\nIndependent Corpus: Potsdam Allahabad (different lab, genre and decade)")
for dv in ["ffd","gaze","gopast","tft"]:
    ra,_ = fit(P, dv, CTRL+" + c_akshara"); rp,n = fit(P, dv, CTRL+" + c_psyll")
    raw,_ = fit(P, dv, CTRL+" + akshara")
    joint,_ = fit(P, dv, CTRL+" + akshara + psyll")
    print(f"  {dv:7s} n={n:6d} dAIC={ra.aic-rp.aic:+9.3f} "
          f"akshara p={raw.pvalues['akshara']:.3g} joint p={joint.pvalues['akshara']:.3g} "
          f"{'Akshara' if ra.aic<rp.aic else 'Spoken'}")

print("\nCross validation on held out readers (5 fold)")
rng = np.random.default_rng(1)
subs = M.subj.unique().copy(); rng.shuffle(subs); folds = np.array_split(subs, 5)
for dv in ["ffd","gaze","gopast"]:
    d = M[(M[dv].notna()) & (M[dv] > 0)].copy(); d["y"] = np.log(d[dv])
    sc = {}
    for name, rhs in [("width only","zipf + wordnum + width_em + C(lab)"),
                      ("akshara","zipf + wordnum + width_em + C(lab) + akshara"),
                      ("spoken","zipf + wordnum + width_em + C(lab) + psyll")]:
        sc[name] = np.mean([np.mean((d[d.subj.isin(f)].y -
                    smf.ols("y ~ "+rhs, d[~d.subj.isin(f)]).fit().predict(d[d.subj.isin(f)]))**2)
                    for f in folds])
    print(f"  {dv:7s} held out MSE " + "  ".join(f"{k}={v:.5f}" for k,v in sc.items())
          + f"   -> {min(sc, key=sc.get).upper()} best")

"""9 The schwa deletion conversion cost and its failure to replicate

Holding akshara count constant, does each deleted schwa cost extra time? This is the one result we do not claim: MECO gaze associations are positive at both laboratories, but
results vary by outcome and reverse sign in the Potsdam Allahabad corpus.
"""

print("MECO pooled + per lab (delta = number of deleted schwas)")
for name, d in [("pooled", M), ("IITK", M[M.lab=="hi_iitk"]), ("IIITH", M[M.lab=="hi_iiith"])]:
    row = []
    for dv in ["ffd","gaze","gopast"]:
        adjusted = d.assign(c_delta=(d.delta-d.delta.mean())/d.delta.std())
        r,_ = fit(adjusted, dv, CTRL+" + c_nchar + c_akshara + c_delta")
        row.append(f"{dv}: b={r.params['c_delta']:+.4f} p={r.pvalues['c_delta']:.2g}")
    print(f"  {name:7s} " + "   ".join(row))

print("\nPAHEC sign reverses")
Pd = P.assign(c_delta=(P.delta-P.delta.mean())/P.delta.std())
for dv in ["gaze","gopast"]:
    r,_ = fit(Pd, dv, CTRL+" + c_nchar + c_akshara + c_delta")
    print(f"  {dv:7s} b={r.params['c_delta']:+.4f} p={r.pvalues['c_delta']:.2g}")

"""10 Effect sizes in milliseconds, and robustness"""

print("Effect sizes (raw, unstandardised)")
for dv, lab in [("ffd","first-fixation"), ("gaze","gaze"), ("gopast","go-past")]:
    d = M[(M[dv].notna()) & (M[dv] > 0)]
    r = smf.ols(f"np.log({dv}) ~ zipf + wordnum + width_em + nchar + akshara + delta + C(lab)", d
                ).fit(cov_type="cluster", cov_kwds={"groups": d["subj"]})
    base = np.exp(r.params["Intercept"] + sum(r.params[k]*d[k].mean()
                  for k in ["zipf","wordnum","width_em","nchar","akshara","delta"]))
    print(f"  {lab:15s} mean={d[dv].mean():6.1f}ms | +1 akshara={base*(np.exp(r.params['akshara'])-1):+6.1f}ms"
          f" | +1 deleted schwa={base*(np.exp(r.params['delta'])-1):+5.1f}ms")

print("\n Robustness (gaze duration; dAIC negative = akshara wins)")
subsets = {
    "all words": M,
    "excluding nukta words": M[~M.nukta.astype(bool)],
    "excluding conjuncts": M[~M.w.astype(str).str.contains(VIRAMA)],
    "only Shabd verified syllabifications": M[M.w.isin(verified)],
    "content words (>=3 chars)": M[M.nchar >= 3],
    "excluding 200 most frequent types": M[~M.w.isin(M.w.value_counts().head(200).index)],
}
for name, s in subsets.items():
    ra,_ = fit(s, "gaze", CTRL+" + c_akshara"); rp,n = fit(s, "gaze", CTRL+" + c_psyll")
    print(f"  {name:38s} n={n:6d}  dAIC={ra.aic-rp.aic:+9.1f}")

"""## 11. Figures"""

fig, ax = plt.subplots(1, 3, figsize=(15, 4.2))

mt = M.drop_duplicates("pos")
ax[0].hist([mt.akshara, mt.psyll], bins=range(1,10), label=["aksharas","spoken syllables"])
ax[0].set_xlabel("units per word"); ax[0].set_ylabel("word positions")
ax[0].set_title("The script writes more units than\nthe language speaks"); ax[0].legend()

rows = [("first fix",ADJUSTED_DAIC["ffd"]),("gaze",ADJUSTED_DAIC["gaze"]),
        ("go past",ADJUSTED_DAIC["gopast"])]
ax[1].barh([r[0] for r in rows], [r[1] for r in rows], color="#b2182b")
ax[1].axvline(0, color="k", lw=.8); ax[1].set_xlabel("$\\Delta$AIC (negative favours akshara)")
ax[1].set_title("Width adjusted comparison\nin MECO duration measures")

g = M[(M.gaze > 0)].groupby("akshara").gaze.mean()
g2 = M[(M.gaze > 0)].groupby("psyll").gaze.mean()
ax[2].plot(g.index, g.values, "o-", label="by akshara count")
ax[2].plot(g2.index, g2.values, "s--", label="by spoken syllable count")
ax[2].set_xlabel("units"); ax[2].set_ylabel("mean gaze duration (ms)")
ax[2].set_title("Descriptive gaze duration\nby the two competing counts"); ax[2].legend()
plt.tight_layout(); plt.savefig("figure1.png", dpi=160); plt.show()

"""12 Exact original Kokila stimulus-image validation

The CC-BY MECO v2.1 stimulus archive contains the actual 2000 × 1000 Hindi stimulus images.
This section downloads the approximately 22.4 MB public archive, unless MECO_BITMAPS_PATH identifies an existing local copy. It extracts original image pixel ink bound widths, not screen/device pixels or glyph advances. A page is accepted only when its segmented word count matches the released word position count and its word by word correlation with independently
shaped Noto widths is at least .98. Matching counts alone are unsafe: pages 4 and 7 pass the count check but have internally misaligned words and must be excluded.

"""

from PIL import Image

bitmap_archive = os.environ.get("MECO_BITMAPS_PATH", "data/meco_wave2_bitmaps.zip")
if not os.path.isfile(bitmap_archive):
    grab("https://osf.io/download/3eu49/", bitmap_archive)
print("Validating original CC-BY MECO v2.1 Hindi images (2000 x 1000 archival pixels)")

accepted_pages, accepted_widths = [], []
with zipfile.ZipFile(bitmap_archive) as source:
    for item in range(1, 13):
        first = source.read(f"Hindi_IITK/Hindi_IITK_{item}.png")
        second = source.read(f"Hindi_IIITH/Hindi_IIITH_{item}.png")
        if first != second:
            raise ValueError(f"Hindi stimulus image differs between sites for page {item}")
        ink = np.asarray(Image.open(io.BytesIO(first)).convert("RGB")).min(axis=2) < 180
        rows = np.flatnonzero(ink.any(axis=1))
        line_groups = np.split(rows, np.flatnonzero(np.diff(rows) > 5) + 1)
        image_widths = []
        for line in line_groups:
            columns = np.flatnonzero(ink[line.min():line.max()+1].any(axis=0))
            words = np.split(columns, np.flatnonzero(np.diff(columns) > 3) + 1)
            image_widths.extend(int(word.max() - word.min() + 1) for word in words)
        page = m[m.item == item]
        expected = int(page.wordnum.max())
        if len(image_widths) != expected:
            print(f"Exclude page={item}: image_words={len(image_widths)}, expected={expected}")
            continue
        widths = pd.DataFrame({"wordnum": np.arange(1, len(image_widths)+1),
                               "bitmap_px": image_widths})
        positions = page[["wordnum", "w", "width_em"]].drop_duplicates()
        aligned = positions.merge(widths, on="wordnum", how="inner")
        correlation = aligned.bitmap_px.corr(aligned.width_em)
        if correlation < .98:
            print(f"Exclude page={item}: count matches but alignment r={correlation:.4f} < .98")
            continue
        print(f"Include page={item}: {len(image_widths)} words, bitmap-vs-Noto r={correlation:.4f}")
        accepted_pages.append(item)
        accepted_widths.append(widths.assign(item=item))

assert accepted_pages == [1, 2, 6, 9, 10, 12], accepted_pages
bitmap_widths = pd.concat(accepted_widths, ignore_index=True)
exact = m.merge(bitmap_widths, on=["item", "wordnum"], how="inner")
unique_positions = exact.drop_duplicates(["item", "wordnum"])
print(f"Validated rows={len(exact):,}, readers={exact.subj.nunique()}, "
      f"pages={exact.item.nunique()}, positions={len(unique_positions):,}, "
      f"word types={exact.w.nunique()}, bitmap-vs-Noto r="
      f"{unique_positions.bitmap_px.corr(unique_positions.width_em):.5f}")

BITMAP_DAIC = {}
for outcome in ["ffd", "gaze", "gopast"]:
    required = [outcome, "zipf", "wordnum", "bitmap_px", "width_em", "akshara", "psyll", "subj", "lab"]
    clean = exact.dropna(subset=required).copy()
    clean = clean[clean[outcome] > 0].copy()
    clean["log_duration"] = np.log(clean[outcome])
    controls = "zipf + wordnum + C(lab) + bitmap_px"
    akshara = smf.ols("log_duration ~ " + controls + " + akshara", clean).fit(
        cov_type="cluster", cov_kwds={"groups": clean.subj})
    spoken = smf.ols("log_duration ~ " + controls + " + psyll", clean).fit(
        cov_type="cluster", cov_kwds={"groups": clean.subj})
    BITMAP_DAIC[outcome] = akshara.aic - spoken.aic
    print(f"Exact original image ink bounds {outcome:7s} n={len(clean):,} "
          f"akshara b={akshara.params['akshara']:+.6f} "
          f"p={akshara.pvalues['akshara']:.3g} dAIC={BITMAP_DAIC[outcome]:+.3f}")
    if outcome == "gaze":
        proxy_controls = "zipf + wordnum + C(lab) + width_em"
        proxy_ak = smf.ols("log_duration ~ " + proxy_controls + " + akshara", clean).fit()
        proxy_spoken = smf.ols("log_duration ~ " + proxy_controls + " + psyll", clean).fit()
        print(f"noto proxy, same validated page: gaze dAIC="
              f"{proxy_ak.aic-proxy_spoken.aic:+.3f}")

"""13 Follow up audit: what the proposed extensions can and cannot establish

The proposed follow up script was written against an earlier, width unadjusted version of
this project. Its additional ideas are useful only after several problems are corrected:

- The landing calculation silently clipped out-of-range character indices, then fitted models to the original land column instead of the newly calculated land_ak column. Neither column contains calibrated pixel coordinates; converting one into the other creates no independent eye tracking measurement.
- The proposed matching operated on repeated reader by word fixation rows, freely reused the same match, counted the same contrast in opposite directions, and controlled neither shaped or image measured width nor reader, site, or item dependence.
- Its sklearn nearest neighbor import was absent from its installation cell. The corrected no replacement matcher below instead uses SciPy, already installed by statsmodels.
- Within any fixed schwa-deletion count, akshara = spoken_syllables + constant`. Models with intercepts therefore have identical fitted values: a better fit in a mixed divergent subgroup can arise only from variation in deletion counts, not merely from written/spoken disagreement.

The checks below retain the validated rendering controls and report their limits explicitly.

13a Character index landing, mapped into akshara ordinals

Only words whose released spelling already equals the punctuation stripped analysis spelling, and only valid in range integer landing indices, are mapped. Invalid coordinates are excluded, never clipped. The resulting akshara ordinal is a deterministic recoding of a character index; it is descriptive, not an independent observation of a physical saccade target.

The inferential comparison therefore retains the original character index response and asks whether adding akshara count changes fit after character count, word frequency, word position, laboratory, and rendered width are already included. Both the full Noto proxy data and the
alignment validated original Kokila image subset are reported.
"""

@lru_cache(maxsize=None)
def akshara_character_map(word):
    """Map each Unicode character to its zero based written akshara ordinal."""
    word = str(word)
    mapping, i, ordinal = [], 0, -1
    while i < len(word):
        point = ord(word[i])
        if point in INDEP_V:
            ordinal += 1
            mapping.append(ordinal)
            i += 1
            while i < len(word) and (ord(word[i]) in SIGNS or word[i] == NUKTA):
                mapping.append(ordinal)
                i += 1
        elif point in CONS:
            ordinal += 1
            mapping.append(ordinal)
            i += 1
            while i < len(word) and word[i] == NUKTA:
                mapping.append(ordinal)
                i += 1
            while i < len(word) and word[i] == VIRAMA:
                mapping.append(ordinal)
                i += 1
                if i < len(word) and ord(word[i]) in CONS:
                    mapping.append(ordinal)
                    i += 1
                    while i < len(word) and word[i] == NUKTA:
                        mapping.append(ordinal)
                        i += 1
                else:
                    break
            if i < len(word) and ord(word[i]) in MATRA:
                mapping.append(ordinal)
                i += 1
            while i < len(word) and (ord(word[i]) in SIGNS or ord(word[i]) in MATRA):
                mapping.append(ordinal)
                i += 1
        else:
            if ordinal < 0:
                return None
            mapping.append(ordinal)
            i += 1
    if not mapping or ordinal + 1 != n_aksharas(word):
        return None
    return tuple(mapping)

candidate_landings = M[(M.land.notna()) & (M.skip == 0)].copy()
unchanged_spelling = candidate_landings.word.astype(str).eq(candidate_landings.w)
integer_coordinate = np.isfinite(candidate_landings.land) & candidate_landings.land.eq(
    np.floor(candidate_landings.land)
)
in_range = candidate_landings.land.ge(1) & candidate_landings.land.le(candidate_landings.nchar)
safe_landings = candidate_landings[unchanged_spelling & integer_coordinate & in_range].copy()
maps = {word: akshara_character_map(word) for word in safe_landings.w.unique()}
safe_landings = safe_landings[safe_landings.w.map(lambda word: maps[word] is not None)].copy()
safe_landings["land_ak"] = [maps[word][int(char_index) - 1] + 1
    for word, char_index in zip(safe_landings.w, safe_landings.land)]

print(f"Candidate non skipped landings: {len(candidate_landings):,}")
print(f"Excluded (changed spelling, invalid index, or ambiguous map): "
      f"{len(candidate_landings)-len(safe_landings):,}")
print(f"Safely mapped landings: {len(safe_landings):,}; "
      f"mean character ordinal={safe_landings.land.mean():.3f}; "
      f"mean akshara ordinal={safe_landings.land_ak.mean():.3f}")

def report_landing_increment(frame, width, label):
    needed = ["land", "zipf", "wordnum", width, "nchar", "akshara", "lab", "subj"]
    data = frame.dropna(subset=needed).copy()
    controls = f"zipf + wordnum + {width} + nchar + C(lab)"
    baseline = smf.ols("land ~ " + controls, data).fit()
    extended = smf.ols("land ~ " + controls + " + akshara", data).fit(
        cov_type="cluster", cov_kwds={"groups": data.subj}
    )
    print(f"{label:26s} n={len(data):,}; extra akshara b="
          f"{extended.params['akshara']:+.4f}; reader clustered p="
          f"{extended.pvalues['akshara']:.3g}; "
          f"AIC change={extended.aic-baseline.aic:+.2f}")

report_landing_increment(safe_landings, "width_em", "Noto shaped width")
image_landings = safe_landings.merge(bitmap_widths, on=["item", "wordnum"], how="inner")
report_landing_increment(image_landings, "bitmap_px", "Original Kokila image width")
print("Interpretation: character index association only; no physical landing coordinate "
      "or causal saccade targeting claim.")

"""14 No replacement matched word schwa deletion sensitivity check

Match distinct word types, not repeated fixation rows, exactly on akshara count and Unicode
character count. Select pairs without replacement by minimum total assignment distance, requiring
an absolute Zipf frequency difference no greater than 0.20 and a relative rendered width
difference no greater than 10%. Run the same procedure three ways: HarfBuzz shaped Noto widths
in MECO, actual original Kokila image ink widths on the six validated MECO pages, and HarfBuzz shaped widths in the fully independent PAHEC corpus. Each pair contains one word with
no deleted schwa and one with at least one deleted schwa.

For each outcome, first average log duration within each (word pair, reader, deletion status) cell; compare only readers who read both paired word types. Regress the within reader deleted minus not deleted difference on residual frequency, rendered width, and text position
differences. Report reader clustered, lexical pair clustered, and two way clustered uncertainty.
Because the assignment is made at the word type level, lexical-pair and two way uncertainty are the relevant conservative checks; reader only significance is not sufficient.

"""

from scipy.optimize import linear_sum_assignment

FREQUENCY_CALIPER, WIDTH_CALIPER = 0.20, 0.10
MATCHED_RESULTS = {}

def matched_deletion_sensitivity(frame, width_column, position_column, source):
    required = ["akshara", "psyll", "nchar", "zipf", width_column, "subj"]
    matching_frame = frame.dropna(subset=required).copy()
    matching_frame["deleted"] = (matching_frame.delta > 0).astype(int)
    matching_frame["matched_width"] = matching_frame[width_column].astype(float)
    matching_frame["matched_position"] = matching_frame[position_column].astype(float)
    word_types = (matching_frame[matching_frame.gaze.notna() & (matching_frame.gaze > 0)]
        .groupby("w", as_index=False)
        .agg(akshara=("akshara", "first"), spoken=("psyll", "first"),
             nchar=("nchar", "first"), zipf=("zipf", "first"),
             matched_width=("matched_width", "median"), deleted=("deleted", "first")))

    pair_records = []
    for _, stratum in word_types.groupby(["akshara", "nchar"]):
        plain = stratum[stratum.deleted == 0].reset_index(drop=True)
        deleted = stratum[stratum.deleted == 1].reset_index(drop=True)
        if plain.empty or deleted.empty:
            continue
        frequency_gap = np.abs(plain.zipf.to_numpy()[:, None] - deleted.zipf.to_numpy()[None, :])
        plain_width = plain.matched_width.to_numpy()[:, None]
        deleted_width = deleted.matched_width.to_numpy()[None, :]
        relative_width_gap = np.abs(plain_width - deleted_width) / ((plain_width + deleted_width) / 2)
        acceptable = (frequency_gap <= FREQUENCY_CALIPER) & (relative_width_gap <= WIDTH_CALIPER)
        assignment_cost = np.where(acceptable,
            frequency_gap / FREQUENCY_CALIPER + relative_width_gap / WIDTH_CALIPER, 1e6)
        plain_rows, deleted_rows = linear_sum_assignment(assignment_cost)
        for plain_index, deleted_index in zip(plain_rows, deleted_rows):
            if not acceptable[plain_index, deleted_index]:
                continue
            ordinary, shortened = plain.iloc[plain_index], deleted.iloc[deleted_index]
            pair_records.append({
                "pair": len(pair_records), "plain": ordinary.w, "deleted_word": shortened.w,
                "akshara": ordinary.akshara, "nchar": ordinary.nchar,
                "plain_spoken": ordinary.spoken, "deleted_spoken": shortened.spoken,
                "zipf_gap": frequency_gap[plain_index, deleted_index],
                "relative_width_gap": relative_width_gap[plain_index, deleted_index],
            })

    matched_word_pairs = pd.DataFrame(pair_records)
    assert matched_word_pairs.plain.is_unique and matched_word_pairs.deleted_word.is_unique
    print(f"\n{source}: {len(matched_word_pairs):,} one to one lexical pairs; "
          f"median absolute Zipf gap={matched_word_pairs.zipf_gap.median():.4f}; "
          f"median relative rendered width gap="
          f"{100*matched_word_pairs.relative_width_gap.median():.2f}%")
    if source == "MECO Noto proxy":
        columns = ["plain", "plain_spoken", "deleted_word", "deleted_spoken", "akshara", "zipf_gap", "relative_width_gap"]
        print("Example real word pairs (no deletion vs. deletion):")
        print(matched_word_pairs.sort_values(["zipf_gap", "relative_width_gap"])
              [columns].head(6).round(4).to_string(index=False))

    word_to_pair = pd.concat([
        matched_word_pairs[["pair", "plain"]].rename(columns={"plain": "w"}),
        matched_word_pairs[["pair", "deleted_word"]].rename(columns={"deleted_word": "w"}),
    ], ignore_index=True)
    matched_observations = matching_frame.merge(word_to_pair, on="w", how="inner")
    MATCHED_RESULTS[source] = {}

    for outcome in ["ffd", "gaze", "gopast"]:
        usable = matched_observations[matched_observations[outcome].notna() &
                                      (matched_observations[outcome] > 0)].copy()
        usable["log_duration"] = np.log(usable[outcome])
        per_reader_word = (usable.groupby(["pair", "subj", "deleted"], observed=True)
            .agg(log_duration=("log_duration", "mean"), frequency=("zipf", "mean"),
                 width=("matched_width", "mean"), word_position=("matched_position", "mean"))
            .reset_index())
        paired = per_reader_word.pivot(index=["pair", "subj"], columns="deleted")
        differences = pd.DataFrame(index=paired.index)
        for field in ["log_duration", "frequency", "width", "word_position"]:
            differences[field + "_difference"] = paired[(field, 1)] - paired[(field, 0)]
        differences = differences.dropna().reset_index()
        model = smf.ols("log_duration_difference ~ frequency_difference + width_difference "
                        "+ word_position_difference", differences)
        readers = pd.factorize(differences.subj)[0]
        lexical_pairs = pd.factorize(differences.pair)[0]
        MATCHED_RESULTS[source][outcome] = {}
        print(f"  {outcome.upper()}: {len(differences):,} within reader paired contrasts; "
              f"{differences.pair.nunique()} lexical pairs; {differences.subj.nunique()} readers")
        for label, clusters in [
            ("reader only", readers), ("lexical pair", lexical_pairs),
            ("reader and lexical pair", np.column_stack([readers, lexical_pairs])),
        ]:
            result = model.fit(cov_type="cluster", cov_kwds={"groups": clusters})
            coefficient = result.params["Intercept"]
            confidence = result.conf_int().loc["Intercept"]
            MATCHED_RESULTS[source][outcome][label] = {
                "log_difference": coefficient, "percentage": 100*np.expm1(coefficient),
                "pvalue": result.pvalues["Intercept"],
                "low": 100*np.expm1(confidence.iloc[0]),
                "high": 100*np.expm1(confidence.iloc[1]),
            }
            print(f"    {label:24s} deletion contrast={100*np.expm1(coefficient):+.2f}% "
                  f"p={result.pvalues['Intercept']:.4g}; "
                  f"95% CI=[{100*np.expm1(confidence.iloc[0]):+.2f}%, "
                  f"{100*np.expm1(confidence.iloc[1]):+.2f}%]")

matched_deletion_sensitivity(M, "width_em", "wordnum", "MECO Noto proxy")
matched_deletion_sensitivity(exact, "bitmap_px", "wordnum", "MECO original Kokila image")
matched_deletion_sensitivity(P, "width_em", "roi", "Independent PAHEC")

print("\nInterpretation: gaze appears positive under reader only clustering, but the "
      "lexical pair and two way tests are not significant, including under original image "
      "width matching and in an independent corpus; no robust deletion cost claim.")

"""15 Divergence localization, with the algebra made explicit

When delta = akshara - spoken_syllables is fixed at any constant, the two competing predictors differ only by an intercept shift and necessarily produce the same fitted values and
AIC. This includes both delta = 0 and delta = 1 words. Therefore a nonzero model comparison advantage among all delta > 0 words merely localizes the contrast to a subgroup containing multiple deletion counts; it does not independently demonstrate orthographic processing or an interaction with divergence.

The check is repeated with independently measured original Kokila stimulus image ink bounds on
the alignment validated six page subset.

"""

DIVERGENCE_RESULTS = {}

def report_divergence(frame, width, source, label):
    required = ["gaze", "zipf", "wordnum", width, "akshara", "psyll", "lab", "subj"]
    data = frame.dropna(subset=required).copy()
    data = data[data.gaze > 0].copy()
    data["log_gaze"] = np.log(data.gaze)
    controls = f"zipf + wordnum + {width} + C(lab)"
    written = smf.ols("log_gaze ~ " + controls + " + akshara", data).fit()
    spoken = smf.ols("log_gaze ~ " + controls + " + psyll", data).fit()
    difference = written.aic - spoken.aic
    fixed_deletion = data.delta.nunique() == 1
    if fixed_deletion:
        assert np.isclose(difference, 0, atol=1e-6), difference
    DIVERGENCE_RESULTS[(source, label)] = {"n": len(data), "aic_difference": difference,
                                          "fixed_deletion": fixed_deletion}
    status = "identical by algebra" if fixed_deletion else "multiple deletion counts"
    print(f"{source:15s} {label:22s} n={len(data):6,}; "
          f"AIC(akshara)-AIC(spoken)={difference:+8.3f}; {status}")

for source, frame, width in [("Noto proxy", M, "width_em"),
                             ("original image", exact, "bitmap_px")]:
    for label, subset in [("all words", frame),
                          ("agreement: delta=0", frame[frame.delta == 0]),
                          ("divergent: delta>0", frame[frame.delta > 0]),
                          ("fixed: delta=1", frame[frame.delta == 1])]:
        report_divergence(subset, width, source, label)

print("\nInterpretation: a mixed delta divergent subgroup localizes where model "
      "differences can occur; fixed delta equivalence is mathematical, not a new finding.")

"""16 Follow up diagnostic figure

The left panel displays how the matched gaze contrast loses statistical precision when its
116 lexical pairs, rather than thousands of repeated reader observations, are respected. The
right panel makes the fixed deletion algebra visible alongside the original image check.

"""

fig, axes = plt.subplots(1, 2, figsize=(12, 4.4))

cluster_labels = ["reader only", "lexical pair", "reader and lexical pair"]
for row, label in enumerate(cluster_labels):
    estimate = MATCHED_RESULTS["MECO Noto proxy"]["gaze"][label]
    x = estimate["percentage"]
    color = "#d35d45" if estimate["pvalue"] < .05 else "#517892"
    axes[0].errorbar(x, row, xerr=[[x-estimate["low"]], [estimate["high"]-x]],
                     fmt="o", capsize=4, color=color, markersize=7)
    axes[0].text(estimate["high"] + .45, row, f"p={estimate['pvalue']:.3f}",
                 va="center", fontsize=9)
axes[0].axvline(0, color="0.35", linewidth=1)
axes[0].set_yticks(range(len(cluster_labels)), cluster_labels)
axes[0].set_xlabel("Matched deleted minus not deleted gaze contrast (%)")
axes[0].set_title("116 matched lexical pairs: inference depends on clustering")

comparisons = [
    ("Noto: delta = 0", ("Noto proxy", "agreement: delta=0")),
    ("Noto: delta = 1", ("Noto proxy", "fixed: delta=1")),
    ("Noto: delta > 0", ("Noto proxy", "divergent: delta>0")),
    ("Original image: delta > 0", ("original image", "divergent: delta>0")),
]
values = [DIVERGENCE_RESULTS[key]["aic_difference"] for _, key in comparisons]
colors = ["#b9c0c7" if abs(value) < 1e-6 else "#2c698a" for value in values]
axes[1].barh([label for label, _ in comparisons], values, color=colors)
axes[1].axvline(0, color="0.35", linewidth=1)
axes[1].set_xlabel("AIC(akshara) - AIC(spoken); negative favors akshara")
axes[1].set_title("Fixed deletion counts are algebraically indistinguishable")
fig.tight_layout()
fig.savefig("figure2_followup_diagnostics.png", dpi=170, bbox_inches="tight")
plt.show()

"""17 Summary

| Claim | Status |
|---|---|
| Akshara effects survive shaped width adjustment in MECO | yes, across first fixation, gaze, and go past durations |
| Akshara effects survive actual Kokila stimulus image ink width adjustment | yes, on six independently alignment validated original pages |
| The effect replicates at both MECO Hindi laboratories | yes, after frequency, position, and width adjustment |
| Independent PAHEC replication is uniform | no: gaze and total time favour aksharas; go past favours spoken syllables |
| Saccades are targeted in akshara space | not established: landing positions are integer character indices |
| A recoded akshara landing ordinal supplies independent eye position evidence | no: it is calculated from the same character index coordinate |
| Matched schwa deletion is robust to lexical item uncertainty | no: reader only gaze association disappears under lexical pair and two way clustering |
| Fixed deletion count subgroup comparisons provide an independent test | no: written and spoken counts differ by a constant within each stratum |
| Predictive improvement is large | no: held out gains are small despite strong statistical evidence |
| Exact Kokila image ink widths are recovered | yes, from the CC-BY original stimulus images; these are image pixels, not screen pixels |

Remaining limitations.The primary full corpus font is an opensource proxy. Exact original
Kokila image ink bounds can be aligned safely for only six texts, and archival image pixels are
not screen/device pixels. Corpus analyses are observational and cannot establish a unique cognitive reading unit, physical landing target, or causal mechanism.

"""